# Generated by Django 4.2.5 on 2023-09-27 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simulations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simulation",
            old_name="application_id",
            new_name="application",
        ),
        migrations.RenameField(
            model_name="simulation",
            old_name="language_id",
            new_name="language",
        ),
        migrations.RenameField(
            model_name="simulation",
            old_name="user_id",
            new_name="user",
        ),
    ]
