# Generated by Django 4.2.5 on 2023-09-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dependencies", "0002_alter_gender_gender_alter_language_language_and_more"),
        ("simulations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dependencies.language",
            ),
        ),
    ]
