# Generated by Django 4.2.5 on 2023-10-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulations", "0002_alter_simulation_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="json_file",
            field=models.TextField(default="[]"),
        ),
    ]
