# Generated by Django 4.2.5 on 2023-10-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulations", "0003_alter_simulation_json_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="json_file",
            field=models.JSONField(default=list),
        ),
    ]
