# Generated by Django 4.2.5 on 2023-10-14 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dependencies", "0001_initial"),
        ("simulations", "0004_alter_simulation_json_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="language",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                to="dependencies.language",
            ),
        ),
    ]
