# Generated by Django 4.2.5 on 2023-09-27 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("dependencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("company_email", models.EmailField(max_length=255)),
                ("company_adress", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                ("recruiter_name", models.CharField(max_length=255)),
                ("recruiter_position", models.CharField(max_length=255)),
                ("status_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "application_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dependencies.language",
                    ),
                ),
                (
                    "recruiter_gender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dependencies.gender",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dependencies.status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
