# Generated by Django 4.2.5 on 2023-09-27 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="application_language_id",
            new_name="application_language",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="recruiter_gender_id",
            new_name="recruiter_gender",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="status_id",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="user_id",
            new_name="user",
        ),
    ]
