# Generated by Django 4.2.5 on 2023-10-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="cover_letter_file",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="application",
            name="cv_file",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
