# Generated by Django 4.2.5 on 2023-09-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dependencies", "0002_alter_gender_gender_alter_language_language_and_more"),
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="application_language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dependencies.language",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="recruiter_gender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dependencies.gender",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dependencies.status",
            ),
        ),
    ]
