# Generated by Django 4.2.5 on 2023-10-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="user",
        ),
        migrations.AddField(
            model_name="application",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
            preserve_default=False,
        ),
    ]
