# Generated by Django 4.2.5 on 2023-10-13 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="cover_letter_file",
        ),
        migrations.RemoveField(
            model_name="application",
            name="cv_file",
        ),
    ]
