# Generated by Django 4.2.5 on 2023-10-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_application_cover_letter_file_application_cv_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="cover_letter_file",
            field=models.FileField(blank=True, upload_to="cover_letter_files/"),
        ),
        migrations.AlterField(
            model_name="application",
            name="cv_file",
            field=models.FileField(blank=True, upload_to="cv_files/"),
        ),
    ]
