# Generated by Django 4.2.5 on 2023-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_remove_application_user_application_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="cv_short_description",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
