# Generated by Django 4.2.5 on 2023-10-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dependencies", "0001_initial"),
        ("applications", "0002_remove_application_cover_letter_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="application_language",
            field=models.ForeignKey(
                default="English",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dependencies.language",
            ),
        ),
    ]
