# Generated by Django 4.2.5 on 2023-10-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_alter_application_cover_letter_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="cover_letter_file",
            field=models.FileField(blank=True, upload_to="saved_files/cover_letters/"),
        ),
        migrations.AlterField(
            model_name="application",
            name="cv_file",
            field=models.FileField(blank=True, upload_to="saved_files/cvs/"),
        ),
    ]
