# Generated by Django 4.2.5 on 2023-10-14 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dependencies", "0001_initial"),
        ("applications", "0003_alter_application_application_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="application_language",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dependencies.language",
            ),
        ),
    ]
