# Generated by Django 4.2.5 on 2023-10-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0004_alter_application_application_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status_date",
            field=models.DateTimeField(),
        ),
    ]
