# Generated by Django 4.2.5 on 2023-10-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0005_alter_application_status_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Saved", "Saved"),
                    ("Applied", "Applied"),
                    ("Scheduled", "Scheduled"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                default="Saved",
                max_length=255,
            ),
        ),
    ]
