# Generated by Django 4.2.5 on 2023-10-19 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0006_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
