# Generated by Django 4.2.5 on 2023-10-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dependencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gender",
            name="gender",
            field=models.CharField(default="Male", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(default="English", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(default="Saved", max_length=100, unique=True),
        ),
    ]
