# Generated by Django 4.2.5 on 2023-10-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
