# Generated by Django 4.2.5 on 2023-10-19 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_alter_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
