# Generated by Django 4.2.5 on 2023-09-27 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="gender_id",
            new_name="gender",
        ),
        migrations.RenameField(
            model_name="userhobby",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="userlanguage",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="userskill",
            old_name="user_id",
            new_name="user",
        ),
    ]
