# Generated by Django 4.2.5 on 2023-09-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="school",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="api_key",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="portfolio_link",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="social_link",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userhobby",
            name="description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userlanguage",
            name="description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="description",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
